#!/bin/bash

apt-get -y update
apt-get -y upgrade

apt-get -y install vim unzip curl psmisc usbmount dos2unix

cd /root

svn co svn://www.drewthejames.com/branches/black_furnace_logger --username nathan --password npwd

cd /root/black_furnace_logger/startup_scripts

cp rc.local /etc/rc.local

if [ ! -f "/root/systemconfig.txt" ];
then
  touch "/root/systemconfig.txt"

  echo  "sitename=\"shocker\"" >> "/root/systemconfig.txt"
  echo  "startingport=\"8000\"" >> "/root/systemconfig.txt"
  echo  "endingport=\"8030\"" >> "/root/systemconfig.txt"
  echo  "username=\"furnace\"" >> "/root/systemconfig.txt"

fi

dos2unix /root/systemconfig.txt

echo ""
echo "*********************************************************************************"
echo ""
echo "Need to set Site Name, User Name, and Port Range in /root/systemconfigg"
echo ""
echo "Need to create ssh key, copy ssh key, and test logging into to backdoor server"
echo ""
echo "Need to add password to root"
echo ""
echo "*********************************************************************************"
echo ""

